### ISSUE TITLE
Notation for IP Address Range

### ISSUE THREAD

**Issue by nabgilby** [fatsecret-group/postman-fatsecret-apis#2]
I really appreciate you adding this example for postman https://github.com/fatsecret-group/postman-fatsecret-apis ( as I have been trying to get a simple food search test with OAuth 2 working in postman and it's been a few days now, really shouldn't be this difficult. I'm trying to get this example working locally in a development environment, on a mac.

I was able to get the OAuth 1.0 working through https.

Not for Autho 2.0:
What is the notation used for an ip address range? It doesn't appear to be CIDR (Classless Inter-Domain Routing)? Can you add an example please? so not 192.168.1.0/24?

But even if I put in a static IP address, I cannot generate an access token. I get Error: invalid_client, I double checked my client_id, client_secret (even generated a new secret) and I just can't get this to work.

Please help! We are developing what might likely be a very high volume app, with lots of marketing behind it and would like to use FatSecret.

**Comment by nabgilby** [comment]
If anyone sees this, you must upgrade to a Premium Free acct :-), THEN you can use the CIDR notation.  Hopefully this will be documented and the error message revised to reflect this.

**Comment by mitchfatsecret** [comment]
Thank you @nabgilby we will add information regarding this in an upcoming release to the platform documentation.
